version: '2'

volumes:
  nextcloud:
  postgresql_var-lib-postgresql-data:

services:
  db:
    image: postgres:12.3-alpine
        
    restart: always
    volumes:
      - postgresql_var-lib-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
 
  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
